# Generated by Django 5.0.1 on 2024-01-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='students',
            field=models.ManyToManyField(related_name='course_students', to='school.studentmodel'),
        ),
    ]
