# Generated by Django 5.0.1 on 2024-01-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_coursemodel_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulemodel',
            name='student',
            field=models.ManyToManyField(related_name='module_students', to='school.studentmodel'),
        ),
    ]
