# Generated by Django 5.0.1 on 2024-02-08 20:59

import django.db.models.deletion
import metsenant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Overall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overal_p', models.PositiveIntegerField()),
                ('overal_ap', models.PositiveIntegerField()),
                ('overal_np', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SponsorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_n', models.CharField(max_length=12)),
                ('payment_q', models.PositiveIntegerField(blank=True, null=True, validators=[metsenant.models.validation_payment_q])),
                ('person', models.CharField(choices=[('legal', 'legal'), ('physical', 'physical')], max_length=30)),
                ('event', models.CharField(choices=[('New', 'new'), ('Moderinization', 'moderinization'), ('Approved', 'approved'), ('Rejected', 'rejected')], default='New', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
            },
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
                ('degree', models.CharField(choices=[("bachelor's", "bachelor's"), ("master's", "master's"), ('doctoral', 'doctoral')], max_length=30)),
                ('contract_q', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='UniversitiesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.CreateModel(
            name='PhysicalPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='metsenant.sponsormodel')),
            ],
        ),
        migrations.CreateModel(
            name='LegalPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_n', models.CharField(max_length=100)),
                ('sponsor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='metsenant.sponsormodel')),
            ],
        ),
        migrations.CreateModel(
            name='SponsorStudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_q', models.PositiveIntegerField(validators=[metsenant.models.validation_money])),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sponsor', to='metsenant.sponsormodel')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='metsenant.studentmodel')),
            ],
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_university', to='metsenant.universitiesmodel'),
        ),
    ]
